import type { Zone } from '../models/zone';
import type { OperationalEvent, IngestSignalPayload, EventTimelineEntry } from '../models/event';
import type { VolunteerTask } from '../models/task';
import type { Incident } from '../models/incident';
import type { SustainabilityMetrics } from '../models/sustainability';
import type { AuditLog } from '../models/audit';
import type { User } from '../models/user';
import type { UserRole } from '../models/role';

/**
 * Service representing real-time and writing interactions with the Firestore database layer.
 */
export interface DatabaseService {
  /**
   * Subscribes to real-time updates for all stadium zones.
   * @param onUpdate Callback fired when zones list is modified.
   * @param onError Callback fired when subscription fails.
   */
  listenToZones(onUpdate: (zones: Zone[]) => void, onError: (err: Error) => void): () => void;

  /**
   * Subscribes to real-time updates for all generated operational events.
   * @param onUpdate Callback fired when events list is modified.
   * @param onError Callback fired when subscription fails.
   */
  listenToEvents(
    onUpdate: (events: OperationalEvent[]) => void,
    onError: (err: Error) => void,
  ): () => void;

  /**
   * Subscribes to tasks assigned to a specific volunteer user.
   * @param volunteerId The unique ID of the target volunteer.
   * @param onUpdate Callback fired when assigned tasks list is modified.
   * @param onError Callback fired when subscription fails.
   */
  listenToTasks(
    volunteerId: string,
    onUpdate: (tasks: VolunteerTask[]) => void,
    onError: (err: Error) => void,
  ): () => void;

  /**
   * Subscribes to real-time updates for security/operational incidents.
   * @param onUpdate Callback fired when incidents list is modified.
   * @param onError Callback fired when subscription fails.
   */
  listenToIncidents(
    onUpdate: (incidents: Incident[]) => void,
    onError: (err: Error) => void,
  ): () => void;

  /**
   * Subscribes to sustainability metrics tracking for a specific match.
   * @param matchId The unique ID of the target match.
   * @param onUpdate Callback fired when sustainability data changes.
   * @param onError Callback fired when subscription fails.
   */
  listenToSustainability(
    matchId: string,
    onUpdate: (metrics: SustainabilityMetrics) => void,
    onError: (err: Error) => void,
  ): () => void;

  /**
   * Subscribes to human audit logs tracking decisions made in response to AI advisories.
   * @param onUpdate Callback fired when audit logs list changes.
   * @param onError Callback fired when subscription fails.
   */
  listenToAuditLogs(
    onUpdate: (logs: AuditLog[]) => void,
    onError: (err: Error) => void,
  ): () => void;

  /**
   * Subscribes to real-time updates for the unified stadium operations timeline.
   * @param onUpdate Callback fired when the timeline is updated.
   * @param onError Callback fired when subscription fails.
   */
  listenToTimeline(
    onUpdate: (timeline: EventTimelineEntry[]) => void,
    onError: (err: Error) => void,
  ): () => void;

  /**
   * Updates the status of a specific volunteer task.
   * @param taskId Unique ID of the task.
   * @param status Next state (pending, in_progress, completed).
   */
  updateTaskStatus(taskId: string, status: VolunteerTask['status']): Promise<void>;

  /**
   * Logs a new security or operational incident.
   * @param incident Incident fields excluding autogenerated metadata.
   */
  reportIncident(incident: Omit<Incident, 'id' | 'timestamp'>): Promise<string>;

  /**
   * Submits a human decision response log for audit auditing.
   * @param log Audit details.
   */
  submitAuditLog(log: Omit<AuditLog, 'id' | 'timestamp'>): Promise<void>;

  /**
   * Blocks or unblocks access pathways for a zone.
   * @param zoneId Target zone ID.
   * @param blocked True to block pathways, false to reopen.
   */
  blockRoute(zoneId: string, blocked: boolean): Promise<void>;

  /**
   * Updates current sustainability metrics fields.
   * @param metrics Partial sustainability values.
   */
  updateSustainability(metrics: Partial<SustainabilityMetrics>): Promise<void>;

  /**
   * Retrieves the current round-trip database read latency.
   */
  getReadLatency(): Promise<number>;
}

/**
 * Service representing interactions with the Gemini AI reasoning wrapper layer.
 */
export interface AIService {
  /**
   * Ingests a telemetry signal to trigger a server-side Gemini decision cycle.
   * @param zoneId Target zone ID.
   * @param type Event type code (e.g. 'turnstile_density').
   * @param payload Structured signal parameters.
   */
  ingestSignal(
    zoneId: string,
    type: string,
    payload: IngestSignalPayload,
  ): Promise<OperationalEvent>;

  /**
   * Requests an AI operational summary digest for a security incident.
   * @param incidentId Target incident ID.
   */
  summarizeIncident(incidentId: string): Promise<string>;

  /**
   * Requests AI analytics and recommendations based on sustainability telemetry.
   * @param metrics Current sustainability metrics values.
   */
  getSustainabilityAdvice(metrics: SustainabilityMetrics): Promise<string>;

  /**
   * Submits a localized question to the fan helper chatbot.
   * @param question Text query.
   * @param language Targeted language code (en, es, fr).
   */
  askAssistant(question: string, language: string): Promise<string>;

  /**
   * Retrieves the current AI engine API latency.
   */
  getAILatency(): Promise<number>;
}

/**
 * Service managing user active session authentication and language/accessibility preference updates.
 */
export interface AuthService {
  /**
   * Retrieves the current authenticated user context or null.
   */
  getCurrentUser(): User | null;

  /**
   * Logs in as a specific role for testing/reviewing.
   * @param role The role to assume.
   */
  loginAsRole(role: UserRole): Promise<User>;

  /**
   * Updates accessibility layout preferences.
   * @param prefs Partial preference parameters.
   */
  updateUserPreferences(prefs: Partial<User['accessibilityPrefs']>): Promise<void>;

  /**
   * Updates user preferred UI locale.
   * @param lang Chosen language code.
   */
  updateUserLanguage(lang: User['language']): Promise<void>;

  /**
   * Listens to user authentication state changes.
   * @param onUpdate Fired when user logs in/out or updates prefs.
   */
  listenToCurrentUser(onUpdate: (user: User | null) => void): () => void;
}

/**
 * Service managing native push and local alert notifications.
 */
export interface NotificationService {
  /**
   * Displays an immediate local system or browser notification.
   * @param title Header title.
   * @param body Description text.
   */
  showLocalNotification(title: string, body: string): void;

  /**
   * Prompts user for system notification permissions.
   */
  requestPermissions(): Promise<boolean>;
}

/**
 * Service managing local task queues and offline storage synchronization.
 */
export interface StorageService {
  /**
   * Retrieves all task updates cached locally while offline.
   */
  getQueuedTasks(): Promise<Omit<VolunteerTask, 'timestamp'>[]>;

  /**
   * Caches a task update locally when connection is lost.
   * @param taskId Task ID.
   * @param status Target status state.
   */
  queueTaskUpdate(taskId: string, status: VolunteerTask['status']): Promise<void>;

  /**
   * Synchronizes and uploads the local cached queue to the live database once online.
   * @param db Target database provider.
   */
  syncOfflineQueue(db: DatabaseService): Promise<void>;

  /**
   * Checks if network is currently connected.
   */
  isOnline(): boolean;

  /**
   * Subscribes to changes in network connectivity.
   * @param onChange Fired when network status toggles.
   */
  listenToConnectionStatus(onChange: (online: boolean) => void): () => void;
}
